- platform: statistics
  name: "Kantoor Alex Power Mean 5min"
  entity_id: sensor.kantoor_alex_power
  state_characteristic: mean
  max_age:
    minutes: 5
- platform: statistics
  name: "Kantoor Joyce Power Mean 5min"
  entity_id: sensor.kantoor_joyce_power
  state_characteristic: mean
  max_age:
    minutes: 5
