########
# Smartmeter sensors
########
- platform: template
  sensors:
    smartmeter_power_consumption:
      friendly_name: Power Consumption
      unit_of_measurement: W
      icon_template: mdi:power-plug
      value_template: "{{ states('input_number.smartmeter_w') | round(1) }}"
      device_class: power
      # state_class: measurement
    smartmeter_total_consumption:
      friendly_name: Total Consumption
      unit_of_measurement: kWh
      icon_template: mdi:sigma
      value_template: "{{ states('input_number.smartmeter_kWh') | round(3) }}"
      device_class: energy
      # state_class: measurement

- platform: statistics
  name: "Kantoor Alex Power Mean 5min"
  entity_id: sensor.kantoor_alex_power
  state_characteristic: mean
  max_age:
    minutes: 5
- platform: statistics
  name: "Kantoor Joyce Power Mean 5min"
  entity_id: sensor.kantoor_joyce_power
  state_characteristic: mean
  max_age:
    minutes: 5
