- platform: systemmonitor
  resources:
    - type: last_boot
    - type: disk_use_percent
      arg: /boot
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: !secret storage_mount
    - type: disk_use_percent
      arg: !secret cache_mount
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: swap_use_percent
    - type: network_in
      arg: !secret network1_device
    - type: network_out
      arg: !secret network1_device
    - type: network_in
      arg: !secret network2_device
    - type: network_out
      arg: !secret network2_device

########
# CPU temperature
########
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

########
# Batterijniveaus rookmelders
########
- platform: template
  sensors:
    rookmelder_hal_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_hal', 'battery_level') }}"
    rookmelder_overloop_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_overloop', 'battery_level') }}"
    rookmelder_zolder_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_zolder', 'battery_level') }}"
    temperatuurverschil_buiten_binnen:
      friendly_name: Temperatuurverschil Buiten-Binnen
      device_class: temperature
      unit_of_measurement: "°C"
      value_template: >
        {% if states.sensor.buiten_temperatuur and states.sensor.woonkamer_temperatuur %}
          {{ (states('sensor.buiten_temperatuur')|float - states('sensor.woonkamer_temperatuur')|float)|round(0)|int }}
        {% endif %}

########
# Smartmeter sensors
########
- platform: template
  sensors:
    smartmeter_power_consumption:
      friendly_name: Power Consumption
      unit_of_measurement: W
      icon_template: mdi:power-plug
      value_template: "{{ states('input_number.smartmeter_w') | round(1) }}"
    smartmeter_total_consumption:
      friendly_name: Total Consumption
      unit_of_measurement: kWh
      icon_template: mdi:sigma
      value_template: "{{ states('input_number.smartmeter_kWh') | round(3) }}"

########
# Meterkast sensors
########
- platform: bme280
  name: Meterkast
