dist: focal
language: python
git:
  depth: 3
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - rm entities/sensors/bme280.yaml
  - rm entities/binary_sensors/rpi_gpio.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
