dist: focal
language: python
git:
  depth: 3
python:
  - "3.9"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - rm entities/sensors/bme280.yml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
