###############################
# Multimedia woonkamer
###############################
- id: scene_select
  alias: Scene Select
  trigger:
    platform: state
    entity_id: input_select.media_scene
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% set scene = trigger.to_state.state %}
          {% if scene == 'Radio luisteren' %}
            script.listen_radio
          {% elif scene == 'TV kijken' %}
            script.watch_tv
          {% elif scene == 'Media kijken' %}
            script.watch_media
          {% else %}
            script.all_media_off
          {% endif %}
- id: check_receiver_source
  alias: Check Receiver source
  initial_state: 'off'
  trigger:
    platform: time
    seconds: '/5'
  action:
    - condition: template
      value_template: '{{ states.media_player.receiver.attributes.source is defined }}'
    - service_template: >
        {% set scene = states.input_select.media_scene.state %}
        {% set source = states.media_player.receiver.attributes.source %}
        {% if scene == 'Geen' or scene == 'TV kijken' and source == 'TV'
            or scene == 'Media kijken' and source == 'Mediaplayer'
            or scene == 'Radio luisteren' and source == 'Radio' %}
          automation.turn_off
        {% else %}
          automation.turn_on
        {% endif %}
      data:
        entity_id: automation.check_receiver_source
    - condition: state
      entity_id: automation.check_receiver_source
      state: 'on'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.receiver
        source: >
          {% if is_state('input_select.media_scene', 'Radio luisteren') %}
            Radio
          {% elif is_state('input_select.media_scene', 'Media kijken') %}
            Mediaplayer
          {% else %}
            TV
          {% endif %}
- id: turn_on_mediaplayer
  alias: Turn on mediaplayer
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: automation.check_receiver_source
    to: 'off'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.media_scene', 'Media kijken') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.mediaspeler

###############################
# Server Control
###############################
#- id: mediaspelers_off
#  alias: Mediaspelers Uit
#  trigger:
#    platform: state
#    entity_id: group.mediaspelers
#    to: 'off'
#  action:
#    - service: script.timed_shutdown_server
#- id: mediaspelers_on
#  alias: Mediaspelers Aan
#  trigger:
#    platform: state
#    entity_id: group.mediaspelers
#    to: 'on'
#  action:
#    - service: script.turn_off
#      entity_id: script.timed_shutdown_server
#    - service: switch.turn_on
#      entity_id: switch.server

###############################
# Home Assistant
###############################
- id: select_logger_level_homeassistant
  alias: Select Logger Level Home Assistant
  trigger:
    platform: state
    entity_id: input_select.logger_level_homeassistant
  action:
    - service: logger.set_level
      data_template:
        homeassistant: "{{ trigger.to_state.state }}"
- id: select_logger_level
  alias: Select Logger Level
  trigger:
    platform: state
    entity_id: input_select.logger_level_zwave
  action:
    - service: logger.set_level
      data_template:
        openzwave: "{{ trigger.to_state.state }}"
    - service: logger.set_level
      data_template:
        libopenzwave: "{{ trigger.to_state.state }}"
    - service: logger.set_level
      data_template:
        homeassistant.components.zwave.util: "{{ trigger.to_state.state }}"
- id: select_logger_level_tradfri
  alias: Select Logger Level Tradfri
  trigger:
    platform: state
    entity_id: input_select.logger_level_tradfri
  action:
    - service: logger.set_level
      data_template:
        pytradfri.coap_cli: "{{ trigger.to_state.state }}"
- id: startup
  alias: Opstarten
  trigger:
    platform: homeassistant
    event: start
  action:
    service: script.initial_select

###############################
# Remote Control
#
# The ZME_RC2 has 11 rows of buttons
# Each button triggers a zwave scene
# The row of the pressed button can be determined with 'scene_id // 10'
# The row-specific scene can be determined with 'scene_id % 10'
# The row-specific scenes which buttons trigger are:
# 
# 1: Short press of the left button
# 2: Short press of the right button
# 3: Initiation of long pressing the left button
# 4: Initiation of long pressing the right button
# 5: Release of long pressing the left button
# 6: Release of long pressing the right button
#
# For now, we only trigger on short press or initiation of long press (<= 4)
# So the side of the button can be determined by '(scene_id % 10) % 2'
# 1: left side
# 0: right side
#
###############################
- id: rc_buttons
  alias: RC Buttons
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
  condition:
    condition: template
    value_template: '{{ (trigger.event.data.scene_id % 10) <= 4 }}'
  action:
    - service: automation.turn_off
      entity_id: automation.holiday_evening_end
    - service: automation.turn_off
      entity_id: automation.holiday_morning_start
    - service: automation.turn_off
      entity_id: automation.holiday_morning_end
    - service_template: >
        {% set row = trigger.event.data.scene_id // 10 %}
        {% set side = (trigger.event.data.scene_id % 10) % 2 %}
        {% if row == 1 %}
          light.turn_{% if side == 1 %}on{% else %}off{% endif %}
        {% elif row >= 8 and row <= 10 %}
          script.turn_on
        {% elif row == 11 %}
          {% if side == 1 %}
            homeassistant.turn_on
          {% else %}
            script.turn_on
          {% endif %}
        {% else %}
          scene.turn_on
        {% endif %}
      data_template:
        entity_id: >
          {% set row = trigger.event.data.scene_id // 10 %}
          {% set side = (trigger.event.data.scene_id % 10) % 2 %}
          {% if row == 1 %}
            light.spruitje
          {% elif row >= 8 and row <= 10 %}
            {% if side == 1 %}
              {% if row == 8 %}
                script.select_tv_kijken
              {% elif row == 9 %}
                script.select_media_kijken
              {% else %}
                script.select_radio_luisteren
              {% endif %}
            {% else %}
              script.select_geen
            {% endif %}
          {% elif row == 11 %}
            {% if side == 1 %}
              group.living_room_lights
            {% else %}
              script.all_off
            {% endif %}
          {% elif side == 1 and row == 2 %}
            scene.woonkamer_regular
          {% elif side == 1 and row == 3 %}
            scene.woonkamer_dim
          {% elif side == 1 and row == 4 %}
            scene.woonkamer_very_dim
          {% else %}
            scene.woonkamer_all_off
          {% endif %}

- id: rf_buttons
  alias: RF Buttons
  trigger:
    platform: state
    entity_id: sensor.sonoff_rf_bridge_rfin
  action:
    - service_template: >
        {% set button = trigger.to_state.state %}
        {% if button == "842162" %}
          fan.turn_on
        {% else %}
          script.turn_on
        {% endif %}
      data_template:
        entity_id: >
          {% set button = trigger.to_state.state %}
          {% if button == "842162" %}
            fan.mechanische_ventilatie
          {% else %}
            script.noop
          {% endif %}

###############################
# Timers licht
###############################
- id: sunset_preparation
  alias: Sunset Preparation
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.sunset_automations
- id: sunset_spruitje
  alias: Sunset spruitje
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  condition:
    condition: state
    entity_id: group.activity_at_home
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.spruitje
- id: sunset_lamp_links_achter
  alias: Sunset lamp links achter
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:25:00'
  condition:
    condition: state
    entity_id: group.activity_at_home
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.linksachter
        brightness: 231
- id: sunset_lamp_links_op_tv_meubel
  alias: Sunset lamp links op tv meubel
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  condition:
    condition: state
    entity_id: group.activity_at_home
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.linksvoor
        brightness: 193
- id: sunset_lamp_schilderij
  alias: Sunset lamp schilderij
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  condition:
    condition: state
    entity_id: group.activity_at_home
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.schilderij
        brightness: 167
- id: sunset_lamp_bij_het_raam
  alias: Sunset lamp bij het raam
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:05:00'
  condition:
    condition: state
    entity_id: group.activity_at_home
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.raam
        brightness: 162
- id: sunset_buitenlamp_voor
  alias: Sunset buitenlamp voor
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:05:00'
  action:
    - service: switch.turn_on
      entity_id: switch.hal_buitenlamp_voor
    - service: automation.turn_on
      entity_id: automation.midnight_buitenlamp_voor
    - service: automation.turn_off
      entity_id: automation.sunset_buitenlamp_voor
- id: midnight_buitenlamp_voor
  alias: Midnight buitenlamp voor
  initial_state: 'off'
  trigger:
    platform: time
    at: '23:05:00'
  action:
    - service: switch.turn_off
      entity_id: switch.hal_buitenlamp_voor
    - service: automation.turn_off
      entity_id: automation.midnight_buitenlamp_voor
    - service: homeassistant.turn_off
      entity_id: group.sunset_automations

###############################
# Vakantietimers
###############################
- id: holiday_evening_start
  alias: Holiday Evening Start
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:05:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.someone_home
        state: 'off'
      - condition: time
        before: '21:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.vakantie
    - service: automation.turn_on
      entity_id: automation.holiday_evening_end
    - service: script.notify_admin
      data:
        message: Vakantietimer geactiveerd
- id: holiday_evening_end
  alias: Holiday Evening End
  initial_state: 'off'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.woonkamer_all_off
    - service: automation.turn_on
      entity_id: automation.holiday_morning_start
    - service: automation.turn_off
      entity_id: automation.holiday_evening_end
- id: holiday_morning_start
  alias: Holiday Morning Start
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  action:
    - service: scene.turn_on
      entity_id: scene.vakantie
    - service: automation.turn_on
      entity_id: automation.holiday_morning_end
    - service: automation.turn_off
      entity_id: automation.holiday_morning_start
- id: holiday_morning_end
  alias: Holiday Morning End
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: scen.turn_on
      entity_id: scene.woonkamer_all_off
    - service: automation.turn_off
      entity_id: automation.holiday_morning_end

###############################
# Slaapkamer
###############################
- id: slaapkamer_tv
  alias: Slaapkamer TV
  trigger:
    platform: state
    entity_id: switch.tv_slaapkamer
  action:
    - service_template: >
        {% if trigger.to_state.state == 'on' %}
          script.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      data_template:
        entity_id: >
          {% if trigger.to_state.state == 'on' %}
            script.tv_slaapkamer_aan
          {% else %}
            light.achterwand_slaapkamer
          {% endif %}
- id: slaapkamer_achterwand
  alias: Slaapkamer Achterwand
  trigger:
    platform: state
    entity_id: light.achterwand_slaapkamer
  action:
    - service_template: >
        {% if trigger.to_state.state == 'on' %}
          script.turn_off
        {% else %}
          script.turn_on
        {% endif %}
      entity_id: script.timer_tv_slaapkamer
- id: RF_slaapkamer_on
  alias: RF Slaapkamer Aan
  trigger:
    platform: state
    entity_id: switch.rf_achterwand_slaapkamer
    to: 'on'
  action:
    - service: light.toggle
      entity_id: light.achterwand_slaapkamer
    - service: switch.turn_off
      entity_id: switch.rf_achterwand_slaapkamer

###############################
# Mechanische ventilatie
###############################
- id: MV Idle
  alias: Mechanische ventilatie stationair
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sensor.mv_vermogen
    above: 1
    below: 15
    for:
      hours: 0
      minutes: 30
      seconds: 0
  action:
    - service: fan.turn_off
      entity_id: fan.mechanische_ventilatie
- id: MV Active
  alias: Mechanische ventilatie aktief
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sensor.mv_vermogen
    above: 15
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
    - condition: state
      entity_id: fan.mechanische_ventilatie
      state: 'on'
    - service: automation.turn_on
      entity_id: automation.mechanische_ventilatie_stationair
- id: Start MV
  alias: Mechanische ventilatie start
  trigger:
    platform: state
    entity_id: fan.mechanische_ventilatie
    to: 'on'
  action:
    - service: automation.turn_on
      entity_id: automation.mechanische_ventilatie_aktief
    - service: automation.turn_off
      entity_id: automation.mechanische_ventilatie_stationair
- id: Stop MV
  alias: Mechanische ventilatie stop
  trigger:
    platform: state
    entity_id: fan.mechanische_ventilatie
    to: 'off'
  action:
    - service: automation.turn_off
      entity_id: automation.mechanische_ventilatie_aktief
    - service: automation.turn_off
      entity_id: automation.mechanische_ventilatie_stationair

