###############################
# Multimedia woonkamer
###############################
- id: scene_select_radio
  alias: Scene Select Radio
  trigger:
    platform: state
    entity_id: input_select.media_scene
    to: 'Radio luisteren'
  action:
    service: script.listen_radio
- id: scene_select_tv
  alias: Scene Select TV
  trigger:
    platform: state
    entity_id: input_select.media_scene
    to: 'TV kijken'
  action:
    service: script.watch_tv
- id: scene_select_media
  alias: Scene Select Media
  trigger:
    platform: state
    entity_id: input_select.media_scene
    to: 'Media kijken'
  action:
    service: script.watch_media
- id: scene_select_geen
  alias: Scene Select Geen
  trigger:
    platform: state
    entity_id: input_select.media_scene
    to: 'Geen'
  action:
    service: script.all_media_off
- id: check_receiver_source
  alias: Check Receiver source
  initial_state: 'off'
  trigger:
    platform: time
    seconds: '/5'
  action:
    - condition: template
      value_template: '{{ states.media_player.receiver.attributes.source is defined }}'
    - service_template: >
        {% set scene = states.input_select.media_scene.state %}
        {% set source = states.media_player.receiver.attributes.source %}
        {% if scene == 'Geen' or scene == 'TV kijken' and source == 'TV' or scene == 'Media kijken' and source in ('TV', 'Mediaplayer') %}
          automation.turn_off
        {% else %}
          automation.turn_on
        {% endif %}
      data:
        entity_id: automation.check_receiver_source
    - condition: state
      entity_id: automation.check_receiver_source
      state: 'on'
    - service: media_player.select_source
      data_template:
        entity_id: media_player.receiver
        source: >
          {% if is_state('input_select.media_scene', 'Radio luisteren') %}
            Radio
          {% else %}
            TV
          {% endif %}
- id: turn_on_mediaplayer
  alias: Turn on mediaplayer
  trigger:
    platform: state
    entity_id: automation.check_receiver_source
    to: 'off'
  condition:
    condition: template
    value_template: "{{ is_state('input_select.media_scene', 'Media kijken') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.mediaspeler
- id: mediaspelers_off
  alias: Mediaspelers Uit
  trigger:
    platform: state
    entity_id: group.mediaspelers
    to: 'off'
  action:
    - service: script.timed_shutdown_server
- id: mediaspelers_on
  alias: Mediaspelers Aan
  trigger:
    platform: state
    entity_id: group.mediaspelers
    to: 'on'
  action:
    - service: script.turn_off
      entity_id: script.timed_shutdown_server
    - service: switch.turn_on
      entity_id: switch.server

###############################
# Home Assistant
###############################
- id: select_logger_level_homeassistant
  alias: Select Logger Level Home Assistant
  trigger:
    platform: state
    entity_id: input_select.logger_level_homeassistant
  action:
    - service: logger.set_level
      data_template:
        homeassistant: "{{ trigger.to_state.state }}"
- id: select_logger_level
  alias: Select Logger Level
  trigger:
    platform: state
    entity_id: input_select.logger_level_zwave
  action:
    - service: logger.set_level
      data_template:
        openzwave: "{{ trigger.to_state.state }}"
    - service: logger.set_level
      data_template:
        libopenzwave: "{{ trigger.to_state.state }}"
    - service: logger.set_level
      data_template:
        homeassistant.components.zwave.util: "{{ trigger.to_state.state }}"
- id: select_logger_level_tradfri
  alias: Select Logger Level Tradfri
  trigger:
    platform: state
    entity_id: input_select.logger_level_tradfri
  action:
    - service: logger.set_level
      data_template:
        pytradfri.coap_cli: "{{ trigger.to_state.state }}"
- id: startup
  alias: Opstarten
  trigger:
    platform: homeassistant
    event: start
  action:
    service_template: >
      {% if is_state('switch.mediaspeler', 'on') %}
        script.select_media_kijken
      {% elif is_state('switch.tv', 'on') %}
        script.select_tv_kijken
      {% elif is_state('switch.receiver', 'on') %}
        script.select_radio_luisteren
      {% else %}
        script.select_geen
      {% endif %}

###############################
# Remote Control
###############################
- id: rc_buttons
  alias: RC Buttons
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remote
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.on_holiday
    - service_template:  >
        {% set row = trigger.event.data.scene_id // 10 %}
        {% set side = trigger.event.data.scene_id % 10 %}
        {% if row >= 1 and row <= 6 %}
          light.turn_{% if side == 1 %}on{% else %}off{% endif %}
        {% elif row == 7 %}
          scene.turn_on
        {% elif row >= 8 and row <= 10 %}
          script.turn_on
        {% elif row == 11 %}
          {% if side == 1 %}
            homeassistant.turn_on
          {% else %}
            script.turn_on
          {% endif %}
        {% endif %}
      data_template: 
        entity_id: >
          {% set row = trigger.event.data.scene_id // 10 %}
          {% set side = trigger.event.data.scene_id % 10 %}
          {% if row == 1 %}
            light.spruitje
          {% elif row == 2 %}
            light.linksvoor
          {% elif row == 3 %}
            light.raam
          {% elif row == 4 %}
            light.achter_bank
          {% elif row == 5 %}
            light.linksachter
          {% elif row == 6 %}
            light.schilderij
          {% elif row == 7 %}
            {% if side == 1 %}
              scene.woonkamer_regular
            {% else %}
              scene.woonkamer_all_off
            {% endif %}
          {% elif row >= 8 and row <= 10 %}
            {% if side == 1 %}
              {% if row == 8 %}
                script.select_tv_kijken
              {% elif row == 9 %}
                script.select_media_kijken
              {% else %}
                script.select_radio_luisteren
              {% endif %}
            {% else %}
              script.select_geen
            {% endif %}
          {% elif row == 11 %}
            {% if side == 1 %}
              group.living_room_lights
           {% else %}
              script.all_off
            {% endif %}
          {% endif %}

###############################
# Timers licht
###############################

- id: sunset_spruitje
  alias: Sunset spruitje
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.spruitje
    - service: input_boolean.turn_off
      entity_id: input_boolean.on_holiday
- id: sunset_lamp_links_achter
  alias: Sunset lamp links achter
  trigger:
    platform: sun
    event: sunset
    offset: '-00:25:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.linksachter
- id: sunset_lamp_links_op_tv_meubel
  alias: Sunset lamp links op tv meubel
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.linksvoor
- id: sunset_lamp_schilderij
  alias: Sunset lamp schilderij
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.schilderij
- id: sunset_lamp_bij_het_raam
  alias: Sunset lamp bij het raam
  trigger:
    platform: sun
    event: sunset
    offset: '-00:05:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.raam
- id: sunset_lamp_achter_de_bank
  alias: Sunset lamp achter de bank
  trigger:
    platform: sun
    event: sunset
    offset: '00:00:00'
  condition:
    condition: state
    entity_id: group.living_room_dependable
    state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.achter_bank

###############################
# Vakantietimers
###############################
- id: holiday_evening_start
  alias: Holiday Evening Start
  trigger:
    platform: sun
    event: sunset
    offset: '+00:05:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: state
        entity_id: group.living_room_dependable
        state: 'off'
      - condition: state
        entity_id: switch.tv_slaapkamer
        state: 'off'
      - condition: time
        before: '21:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: group.lights_vacation
    - service: input_boolean.turn_on
      entity_id: input_boolean.on_holiday
    - service: script.notify_admin
      data:
        message: Vakantietimer geactiveerd
- id: holiday_evening_end
  alias: Holiday Evening End
  trigger:
    platform: sun
    event: sunset
    offset: '+02:05:00'
  condition:
    condition: state
    entity_id: input_boolean.on_holiday
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_vacation
- id: holiday_morning_start
  alias: Holiday Morning Start
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.on_holiday
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.lights_vacation
- id: holiday_morning_end
  alias: Holiday Morning End
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: state
    entity_id: input_boolean.on_holiday
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.lights_vacation

###############################
# Slaapkamer
###############################
- id: slaapkamer_on
  alias: Slaapkamer Aan
  trigger:
    platform: state
    entity_id: switch.tv_slaapkamer
    to: 'on'
  action:
    - service: script.turn_off
      entity_id: script.prepare_for_bed
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon' 
    - service: light.turn_on
      entity_id: light.achterwand_slaapkamer
- id: slaapkamer_off
  alias: Slaapkamer Uit
  trigger:
    platform: state
    entity_id: switch.tv_slaapkamer
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.achterwand_slaapkamer
- id: detect_slaapkamer_on
  alias: Detect Slaapkamer Aan
  trigger:
    platform: state
    entity_id: light.achterwand_slaapkamer
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.rf_achterwand_slaapkamer
- id: detect_slaapkamer_off
  alias: Detect Slaapkamer Uit
  trigger:
    platform: state
    entity_id: light.achterwand_slaapkamer
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.rf_achterwand_slaapkamer
- id: RF_slaapkamer_on
  alias: RF Slaapkamer Aan
  trigger:
    platform: state
    entity_id: switch.rf_achterwand_slaapkamer
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.achterwand_slaapkamer
- id: RF_slaapkamer_off
  alias: RF Slaapkamer Uit
  trigger:
    platform: state
    entity_id: switch.rf_achterwand_slaapkamer
    to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.achterwand_slaapkamer

