- platform: mqtt
  name: "Sonoff POW status"
  state_topic: "sonoff/pow-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH status"
  state_topic: "sonoff/4ch-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH PRO status"
  state_topic: "sonoff/4chpro-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff S20 status"
  state_topic: "sonoff/s20-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff RF Bridge status"
  state_topic: "sonoff/rfbridge-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"

- platform: template
  sensors:
    alex_home:
      friendly_name: "Alex is thuis"
      value_template: "{{ is_state('device_tracker.alex', 'home') }}"
    joyce_home:
      friendly_name: "Joyce is thuis"
      value_template: "{{ is_state('device_tracker.joyce', 'home') }}"
    rook_hal:
      friendly_name: "Rook in de Hal"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_hal_smoke', '2') }}"
    test_rookmelder_hal:
      friendly_name: "TEST Rookmelder Hal"
      value_template: "{{ is_state('sensor.rookmelder_hal_smoke', '3') }}"
    rook_overloop:
      friendly_name: "Rook op de Overloop"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_overloop_smoke', '2') }}"
    test_rookmelder_overloop:
      friendly_name: "TEST Rookmelder Overloop"
      value_template: "{{ is_state('sensor.rookmelder_overloop_smoke', '3') }}"
    rook_zolder:
      friendly_name: "Rook op Zolder"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_zolder_smoke', '2') }}"
    test_rookmelder_zolder:
      friendly_name: "TEST Rookmelder Zolder"
      value_template: "{{ is_state('sensor.rookmelder_zolder_smoke', '3') }}"

