- platform: mqtt
  name: "Sonoff POW status"
  state_topic: "homeassistant/switch/sonoff_pow_1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH status"
  state_topic: "homeassistant/switch/sonoff_4ch_1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH PRO status"
  state_topic: "homeassistant/switch/sonoff_4chpro_1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff S20 status"
  state_topic: "homeassistant/switch/sonoff_s20_1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff RF Bridge status"
  state_topic: "homeassistant/switch/sonoff_rfbr_1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
#- platform: mqtt
#  name: "Sonoff Dual status"
#  state_topic: "homeassistant/switch/sonoff_dual_1/status"
#  device_class: connectivity
#  payload_on: "1"
#  payload_off: "0"

- platform: template
  sensors:
    alex_home:
      friendly_name: "Alex is thuis"
      value_template: "{{ is_state('device_tracker.alex', 'home') }}"
    joyce_home:
      friendly_name: "Joyce is thuis"
      value_template: "{{ is_state('device_tracker.joyce', 'home') }}"

