- platform: mqtt
  name: "Sonoff POW status"
  state_topic: "sonoff/pow-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH status"
  state_topic: "sonoff/4ch-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff 4CH PRO status"
  state_topic: "sonoff/4chpro-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff S20 status"
  state_topic: "sonoff/s20-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Sonoff RF Bridge status"
  state_topic: "sonoff/rfbridge-1/status"
  device_class: connectivity
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  name: "Rookmelder Hal"
  payload_on: true
  payload_off: false
  value_template: "{{ value_json.smoke }}"
  device_class: smoke
  json_attributes:
    - battery
    - voltage
  state_topic: "zigbee2mqtt/0x00158d0002311adc"
  availability_topic: "zigbee2mqtt/bridge/state"
  unique_id: "0x00158d0002311adc_smoke_zigbee2mqtt"

- platform: template
  sensors:
    alex_home:
      friendly_name: "Alex is thuis"
      value_template: "{{ is_state('device_tracker.alex', 'home') }}"
    joyce_home:
      friendly_name: "Joyce is thuis"
      value_template: "{{ is_state('device_tracker.joyce', 'home') }}"
