homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  customize: !include customize.yaml

default_config:

logger: !include logger.yaml
recorder:
  purge_keep_days: 1
influxdb: !include influxdb.yaml
notify: !include notify.yaml
group: !include groups.yaml
media_player: !include mediaplayer.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
timer: !include timer.yaml
