homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

config:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:


# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Text to speech
#tts:
#  platform: google

zeroconf:
logger: !include logger.yaml
recorder: !include recorder.yaml
zwave: !include zwave.yaml
influxdb: !include influxdb.yaml
notify: !include notify.yaml
group: !include groups.yaml
media_player: !include mediaplayer.yaml
sensor: !include sensor.yaml
fan: !include fan.yaml
switch: !include switch.yaml
light: !include light.yaml
mqtt: !include mqtt.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
automation: !include automations.yaml
device_tracker: !include device_tracker.yaml
script: !include scripts.yaml
shell_command: !include shell_command.yaml
