#- platform: ping
#  interval_seconds: 10
#  count: 1
#  consider_home: 20
#  hosts:
#    woonkamer: !secret host_woonkamer
#    slaapkamer: !secret host_slaapkamer
#    televisie: !secret host_televisie
- platform: ping
  interval_seconds: 60
  count: 1
  hosts:
    alex: !secret host_alex
    joyce: !secret host_joyce
