- platform: mqtt
  name: Mechanische ventilatie
  state_topic: "homeassistant/switch/sonoff_pow_1/relay/0"
  command_topic: "homeassistant/switch/sonoff_pow_1/relay/0/set"
  payload_off: "0"
  payload_on: "1"
