- platform: mqtt
  name: Spruitje
  state_topic: "sonoff/4ch-1/relay/2"
  command_topic: "sonoff/4ch-1/relay/2/set"
  payload_off: "0"
  payload_on: "1"
- platform: mqtt
  name: Nachtlampje Alex
  state_topic: "sonoff/4chpro-1/relay/0"
  command_topic: "sonoff/4chpro-1/relay/0/set"
  payload_off: "0"
  payload_on: "1"
- platform: mqtt
  name: Nachtlampje Joyce
  state_topic: "sonoff/4chpro-1/relay/1"
  command_topic: "sonoff/4chpro-1/relay/1/set"
  payload_off: "0"
  payload_on: "1"

