title: Admin
views:
  - badges: []
    cards:
      - entities:
          - entity: input_boolean.admin_notifications
        show_header_toggle: false
        title: Toggles
        type: entities
      - entities:
          - entity: input_select.logger_level_default
          - entity: input_select.logger_level_homeassistant
          - entity: input_select.logger_level_zwave
          - entity: input_select.logger_level_zigbee
          - entity: input_select.logger_level_esphome
        title: Logging Levels
        type: entities
    icon: "mdi:cog"
    title: Settings
