title: Admin
views:
  - badges: []
    cards:
      - entities:
          - entity: input_boolean.admin_notifications
        show_header_toggle: false
        title: Toggles
        type: entities
      - entities:
          - entity: input_select.logger_level_default
          - entity: input_select.logger_level_homeassistant
          - entity: input_select.logger_level_zwave
          - entity: input_select.logger_level_zigbee
          - entity: input_select.logger_level_esphome
        title: Logging Levels
        type: entities
    icon: "mdi:cog"
    title: Settings
  - badges: []
    cards:
      - entities:
          - entity: sensor.slaapkamer_ip_address
          - entity: sensor.slaapkamer_achterwand_ip_address
          - entity: sensor.garage_ip_address
          - entity: sensor.smartmeter_ip_address
          - entity: sensor.tv_meubel_ip_address
          - entity: sensor.ventilatie_ip_address
          - entity: sensor.veranda_verlichting_ip_address
          - entity: sensor.zolder_ip_address
        show_header_toggle: false
        title: Esphome
        type: entities
    icon: "mdi:switch"
    title: Sonoff
