- platform: yr
- platform: dsmr
  port: /dev/smartmeter
  dsmr_version: 4
- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: disk_use_percent
      arg: /boot
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: !secret storage_mount
    - type: disk_use_percent
      arg: !secret cache_mount
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: swap_use_percent
    - type: network_in
      arg: !secret network1_device
    - type: network_out
      arg: !secret network1_device
    - type: network_in
      arg: !secret network2_device
    - type: network_out
      arg: !secret network2_device
    - type: network_in
      arg: !secret network3_device
    - type: network_out
      arg: !secret network3_device

########
# CPU temperature
########
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

########
# Sonoff MQTT sensors
########
- platform: mqtt
  name: "MV vermogen"
  state_topic: "sonoff/pow-1/power"
  unit_of_measurement: "W"
- platform: mqtt
  name: "MV stroom"
  state_topic: "sonoff/pow-1/current"
  unit_of_measurement: "A"
- platform: mqtt
  name: "MV spanning"
  state_topic: "sonoff/pow-1/voltage"
  unit_of_measurement: "V"
- platform: mqtt
  name: "MV actief vermogen"
  state_topic: "sonoff/pow-1/apparent"
  unit_of_measurement: "VA"
- platform: mqtt
  name: "MV reactief vermogen"
  state_topic: "sonoff/pow-1/reactive"
  unit_of_measurement: "VAR"
- platform: mqtt
  name: "MV power factor"
  state_topic: "sonoff/pow-1/factor"
- platform: mqtt
  name: "Sonoff POW uptime"
  state_topic: "sonoff/pow-1/uptime"
- platform: mqtt
  name: "Sonoff POW freeheap"
  state_topic: "sonoff/pow-1/freeheap"
- platform: mqtt
  name: "Sonoff POW rssi"
  state_topic: "sonoff/pow-1/rssi"
  unit_of_measurement: "dB"
- platform: mqtt
  name: "Sonoff POW version"
  state_topic: "sonoff/pow-1/version"
- platform: mqtt
  name: "Sonoff 4CH uptime"
  state_topic: "sonoff/4ch-1/uptime"
- platform: mqtt
  name: "Sonoff 4CH freeheap"
  state_topic: "sonoff/4ch-1/freeheap"
- platform: mqtt
  name: "Sonoff 4CH rssi"
  state_topic: "sonoff/4ch-1/rssi"
  unit_of_measurement: "dB"
- platform: mqtt
  name: "Sonoff 4CH version"
  state_topic: "sonoff/4ch-1/version"
- platform: mqtt
  name: "Sonoff 4CH PRO uptime"
  state_topic: "sonoff/4chpro-1/uptime"
- platform: mqtt
  name: "Sonoff 4CH PRO freeheap"
  state_topic: "sonoff/4chpro-1/freeheap"
- platform: mqtt
  name: "Sonoff 4CH PRO rssi"
  state_topic: "sonoff/4chpro-1/rssi"
  unit_of_measurement: "dB"
- platform: mqtt
  name: "Sonoff 4CH PRO version"
  state_topic: "sonoff/4chpro-1/version"
- platform: mqtt
  name: "Sonoff S20 uptime"
  state_topic: "sonoff/s20-1/uptime"
- platform: mqtt
  name: "Sonoff S20 freeheap"
  state_topic: "sonoff/s20-1/freeheap"
- platform: mqtt
  name: "Sonoff S20 rssi"
  state_topic: "sonoff/s20-1/rssi"
  unit_of_measurement: "dB"
- platform: mqtt
  name: "Sonoff S20 version"
  state_topic: "sonoff/s20-1/version"
- platform: mqtt
  name: "Sonoff RF Bridge uptime"
  state_topic: "sonoff/rfbridge-1/uptime"
- platform: mqtt
  name: "Sonoff RF Bridge freeheap"
  state_topic: "sonoff/rfbridge-1/freeheap"
- platform: mqtt
  name: "Sonoff RF Bridge rssi"
  state_topic: "sonoff/rfbridge-1/rssi"
  unit_of_measurement: "dB"
- platform: mqtt
  name: "Sonoff RF Bridge version"
  state_topic: "sonoff/rfbridge-1/version"
- platform: mqtt
  name: "Sonoff RF Bridge rfin"
  state_topic: "sonoff/rfbridge-1/rfin"
  value_template: "{{value[-6:]}}"
