- platform: yr
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: disk_use_percent
      arg: /boot
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: !secret storage_mount
    - type: disk_use_percent
      arg: !secret cache_mount
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: memory_use_percent
    - type: swap_use_percent
    - type: network_in
      arg: !secret network1_device
    - type: network_out
      arg: !secret network1_device
    - type: network_in
      arg: !secret network2_device
    - type: network_out
      arg: !secret network2_device

########
# CPU temperature
########
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

########
# Batterijniveaus rookmelders
########
- platform: template
  sensors:
    rookmelder_hal_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_hal', 'battery_level') }}"
    rookmelder_overloop_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_overloop', 'battery_level') }}"
    rookmelder_zolder_battery_level:
      friendly_name: "Batterijniveau"
      device_class: battery
      value_template: "{{ state_attr('zwave.rookmelder_zolder', 'battery_level') }}"
    temperatuurverschil_buiten_binnen:
      friendly_name: Temperatuurverschil Buiten-Binnen
      device_class: temperature
      value_template: "{{ (states('sensor.buiten_temperatuur')|float - states('sensor.woonkamer_temperatuur')|float)|round(1) }}"

