- platform: wake_on_lan
  name: NUC
  mac_address: !secret mac_nuc
  host: nuc
  turn_off:
    service: shell_command.turn_off_nuc
- platform: wake_on_lan
  name: Server
  mac_address: !secret mac_server
  host: server
  turn_off:
    service: shell_command.turn_off_server
