title: Home
views:
  - badges:
      - entity: binary_sensor.rookmelder_woonkamer_smoke_detected
      - entity: sensor.rookmelder_woonkamer_battery_level
      - entity: binary_sensor.rookmelder_hal_smoke_detected
      - entity: sensor.rookmelder_hal_battery_level
    cards:
      - entities:
          - entity: input_select.media_scene
          - entity: input_select.light_scene
        show_header_toggle: false
        title: Scene Selectie
        type: entities
      - entities:
          - entity: light.tv_meubel_spruitje
          - entity: light.linksvoor
          - entity: light.raam
          - entity: light.linksachter
          - entity: light.schilderij
          - entity: light.eettafel
          - entity: light.kerstboom
          - entity: script.all_off
        show_header_toggle: true
        title: Woonkamer
        type: entities
      - entities:
          - entity: light.verlichting_keuken
          - entity: switch.hal_lamp
          - entity: light.licht_toilet
        show_header_toggle: false
        title: Overig
        type: entities
      - entities:
          - entity: media_player.receiver
          - entity: media_player.tv
          - entity: switch.tv_meubel_mediaplayer
          - entity: media_player.woonkamer
        show_header_toggle: false
        title: Multimedia
        type: entities
    icon: "mdi:home-assistant"
    panel: false
    path: default_view
    title: Woonkamer
  - badges:
      - entity: binary_sensor.rookmelder_overloop_smoke_detected
      - entity: sensor.rookmelder_overloop_battery_level
      - entity: sensor.licht_slaapkamer_electric_consumption_w
      - entity: sensor.licht_slaapkamer_electric_consumption_kwh
      - entity: sensor.licht_studiekamer_electric_consumption_w
      - entity: sensor.licht_studiekamer_electric_consumption_kwh
      - entity: sensor.licht_kledingkamer_electric_consumption_w
      - entity: sensor.licht_kledingkamer_electric_consumption_kwh
      - entity: sensor.licht_badkamer_electric_consumption_w
      - entity: sensor.licht_badkamer_electric_consumption_kwh
      - entity: sensor.wastafel_badkamer_electric_consumption_w
      - entity: sensor.wastafel_badkamer_electric_consumption_kwh
      - entity: sensor.kantoor_joyce_power
      - entity: sensor.kantoor_joyce_power_mean_5min
      - entity: sensor.kantoor_joyce_electric_consumption_kwh
    cards:
      - entities:
          - entity: switch.overloop_lamp
        show_header_toggle: false
        title: Overloop
        type: entities
      - entities:
          - entity: light.licht_slaapkamer
          - entity: light.slaapkamer_achterwand
          - entity: switch.slaapkamer_tv
          - entity: light.nachtlampje_alex
          - entity: light.nachtlampje_joyce
          - entity: timer.tv_slaapkamer
          - entity: input_boolean.evening_trigger_upstairs
          - entity: timer.timeout_activity_upstairs
        show_header_toggle: false
        title: Slaapkamer
        type: entities
      - entities:
          - entity: light.licht_studiekamer
          - entity: switch.kantoor_joyce
          - entity: automation.kantoor_joyce_auto_turn_off
        show_header_toggle: false
        title: Studiekamer
        type: entities
      - entities:
          - entity: light.licht_kledingkamer
        show_header_toggle: false
        title: Kledingkamer
        type: entities
      - entities:
          - entity: light.licht_badkamer
          - entity: light.wastafel_badkamer
        show_header_toggle: false
        title: Badkamer
        type: entities
    icon: "mdi:home-floor-1"
    title: 1e Verdieping
  - badges:
      - entity: binary_sensor.rookmelder_zolder_smoke_detected
      - entity: sensor.rookmelder_zolder_battery_level
      - entity: binary_sensor.koolmonoxidemelder_carbon_monoxide_detected
      - entity: sensor.koolmonoxidemelder_carbon_monoxide_co_level
      - entity: sensor.koolmonoxidemelder_battery_level
      - entity: sensor.kantoor_alex_power
      - entity: sensor.kantoor_alex_power_mean_5min
      - entity: sensor.kantoor_alex_electric_consumption_kwh
      - entity: sensor.mechanische_ventilatie_power
    cards:
      - entities:
          - entity: light.zolder
        show_header_toggle: false
        title: Zolder
        type: entities
      - entities:
          - entity: light.kantoor
          - entity: switch.zolder_pc
          - entity: switch.zolder_printer
          - entity: light.zolder_bureaulamp
          - entity: switch.kantoor_alex
          - entity: automation.kantoor_auto_turn_off
        show_header_toggle: false
        title: Kantoor Alex
        type: entities
      - entities:
          - entity: fan.mechanische_ventilatie
          - entity: sensor.mechanische_ventilatie_power
          - entity: automation.mechanische_ventilatie_auto_off
        show_header_toggle: false
        title: Mechanische Ventilatie
        type: entities
    icon: "mdi:home-roof"
    title: Zolder
  - badges:
      - entity: sensor.buitensensor_air_temperature
    cards:
      - entities:
          - entity: light.schakelaars_hal_2
          - entity: light.buitenverlichting_achter
          - entity: light.buitenverlichting_garage
          - entity: light.buitenverlichting_veranda
          - entity: light.kerstverlichting_buiten
          - entity: light.kerstverlichting_voor
          - entity: cover.zonwering_achter
        show_header_toggle: false
        title: Bediening Buiten
        type: entities
    icon: "mdi:home-city"
    title: Buiten
  - badges:
      - entity: sensor.binnentemperatuur
      - entity: sensor.temperatuur_range_binnen
      - entity: sensor.buitensensor_air_temperature
      - entity: sensor.temperatuur_range
      - entity: sensor.luchtvochtigheid_binnen
      - entity: sensor.luchtdruk
      - entity: sun.sun
    cards:
      - entities:
          - entity: weather.home
        show_header_toggle: false
        type: entities
      - entities:
          - entity: sensor.buitensensor_air_temperature
            name: Buitentemperatuur
        show_header_toggle: false
        title: Buitensensor
        type: entities
      - entities:
          - entity: sensor.slaapkamer_temperatuur
            name: Temperatuur
          - entity: sensor.slaapkamer_luchtvochtigheid
            name: Luchtvochtigheid
          - entity: sensor.slaapkamer_luchtdruk
            name: Luchtdruk
        show_header_toggle: false
        title: Slaapkamer
        type: entities
      - entities:
          - entity: sensor.woonkamer_temperatuur
            name: Kast Temperatuur
          - entity: sensor.esp32_bluetooth_proxy_800c8c_woonkamer_temperatuur
            name: TV Meubel Temperatuur
          - entity: sensor.esp32_bluetooth_proxy_800c8c_woonkamer_luchtvochtigheid
            name: TV Meubel Luchtvochtigheid
          - entity: sensor.esp32_bluetooth_proxy_800c8c_woonkamer_luchtdruk
            name: TV Meubel Luchtdruk
          - entity: sensor.zonwering_remote_air_temperature
            name: Buitendeur Temperatuur
        show_header_toggle: false
        title: Woonkamer
        type: entities
      - entities:
          - entity: sensor.rookmelder_zolder_air_temperature
            name: Zolder
          - entity: sensor.rookmelder_overloop_air_temperature
            name: Overloop
          - entity: sensor.rookmelder_hal_air_temperature
            name: Hal
          - entity: sensor.rookmelder_woonkamer_air_temperature
            name: Woonkamer
          - entity: sensor.koolmonoxidemelder_air_temperature
            name: Washok
        show_header_toggle: false
        title: Temperaturen Rookmelders
        type: entities
      - entities:
          - entity: sensor.temperatuurverschil_buiten_binnen
        show_header_toggle: false
        title: Temperatuurmonitoring
        type: entities
    icon: "mdi:thermometer-lines"
    title: Klimaat
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.rookmelder_hal_smoke_detected
          - entity: sensor.rookmelder_hal_battery_level
        show_header_toggle: false
        title: Rookmelder Hal
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_overloop_smoke_detected
          - entity: sensor.rookmelder_overloop_battery_level
        show_header_toggle: false
        title: Rookmelder Overloop
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_zolder_smoke_detected
          - entity: sensor.rookmelder_zolder_battery_level
        show_header_toggle: false
        title: Rookmelder Zolder
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_woonkamer_smoke_detected
          - entity: sensor.rookmelder_woonkamer_battery_level
        show_header_toggle: false
        title: Rookmelder Woonkamer
        type: entities
      - entities:
          - entity: binary_sensor.koolmonoxidemelder_carbon_monoxide_detected
          - entity: sensor.koolmonoxidemelder_carbon_monoxide_co_level
          - entity: sensor.koolmonoxidemelder_battery_level
        show_header_toggle: false
        title: CO Melder
        type: entities
    icon: "mdi:shield-check"
    title: Veiligheid
  - badges: []
    cards:
      - entities:
          - entity: media_player.receiver
          - entity: media_player.woonkamer
          - entity: media_player.slaapkamer
        show_state: false
        show_header_toggle: true
        title: Mediaspelers
        type: glance
    icon: "mdi:desktop-classic"
    title: Apparaten
  - badges:
      - entity: person.alex
      - entity: person.joyce
      - entity: sun.sun
    cards:
      - entities:
          - entity: sensor.power_consumption
            name: Power Consumption
        show_header_toggle: false
        type: entities
      - entities:
          - entity: sensor.last_boot
          - entity: sensor.processor_use
          - entity: sensor.system_monitor_processor_temperature
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.memory_use_percent
          - entity: sensor.swap_use_percent
          - entity: sensor.disk_use_percent
          - entity: sensor.disk_use_percent_boot
          - entity: sensor.disk_use_percent_storage
          - entity: sensor.network_in_eth0
          - entity: sensor.network_out_eth0
          - entity: sensor.network_in_eth1
          - entity: sensor.network_out_eth1
        show_header_toggle: false
        title: PiCore1
        type: entities
      - entities:
          - entity: binary_sensor.sda_spinning
            name: SDA Spinning
          - entity: binary_sensor.sdb_spinning
            name: SDB Spinning
        show_header_toggle: false
        type: entities
    icon: "mdi:speedometer"
    title: Monitoring
