title: Home
views:
  - badges: []
    cards:
      - entities:
          - entity: input_select.media_scene
          - entity: input_select.light_scene
        show_header_toggle: false
        title: Scene Selectie
        type: entities
      - entities:
          - entity: light.tv_meubel_spruitje
          - entity: light.linksvoor
          - entity: light.raam
          - entity: light.linksachter
          - entity: light.schilderij
          - entity: light.eettafel
          - entity: switch.kerstboom
          - entity: script.all_off
        show_header_toggle: true
        title: Verlichting
        type: entities
    icon: "mdi:home-assistant"
    panel: false
    path: default_view
    title: Woonkamer
  - badges: []
    cards:
      - entities:
          - entity: light.slaapkamer_achterwand
          - entity: switch.slaapkamer_tv
          - entity: light.nachtlampje_alex
          - entity: light.nachtlampje_joyce
          - entity: timer.tv_slaapkamer
          - entity: input_boolean.evening_trigger_upstairs
          - entity: timer.timeout_activity_upstairs
        show_header_toggle: false
        title: Slaapkamer
        type: entities
    icon: "mdi:sleep"
    title: Slaapkamer
  - badges: []
    cards:
      - entities:
          - entity: switch.hal_lamp
          - entity: switch.hal_buitenlamp_voor
          - entity: switch.overloop_lamp
          - entity: light.veranda_verlichting
          - entity: light.kerstverlichting_buiten
          - entity: light.kerstverlichting_voor
        title: Overige Lampen
        type: entities
      - entities:
          - entity: light.zolder
        show_header_toggle: false
        title: Zolder
        type: entities
      - entities:
          - entity: light.kantoor
          - entity: switch.zolder_pc
          - entity: switch.zolder_printer
          - entity: light.zolder_bureaulamp
          - entity: switch.kantoor_alex
          - entity: sensor.kantoor_alex_power
          - entity: sensor.kantoor_alex_energy
        show_header_toggle: false
        title: Kantoor Alex
        type: entities
      - entities:
          - entity: switch.kantoor_joyce
          - entity: sensor.kantoor_joyce_power
          - entity: sensor.kantoor_joyce_energy
        show_header_toggle: false
        title: Kantoor Joyce
        type: entities
      - entities:
          - entity: media_player.receiver
          - entity: media_player.coreelec
          - entity: media_player.slaapkamer
        show_state: false
        title: Mediaspelers
        type: glance
      - entities:
          - entity: switch.ventilatie
          - entity: sensor.ventilatie_power
          - entity: sensor.ventilatie_voltage
          - entity: sensor.ventilatie_current
          - entity: switch.ventilatie_auto_poweroff
        show_header_toggle: false
        title: Mechanische Ventilatie
        type: entities
    icon: "mdi:desktop-classic"
    title: Apparaten
  - badges: []
    cards:
      - entities:
          - entity: binary_sensor.rookmelder_hal_smoke_alarm_smoke_detected
          - entity: binary_sensor.rookmelder_hal_smoke_alarm_smoke_alarm_test
          - entity: sensor.rookmelder_hal_battery_level
        show_header_toggle: false
        title: Rookmelder Hal
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_overloop_smoke_alarm_smoke_detected
          - entity: binary_sensor.rookmelder_overloop_smoke_alarm_smoke_alarm_test
          - entity: sensor.rookmelder_overloop_battery_level
        show_header_toggle: false
        title: Rookmelder Overloop
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_zolder_smoke_alarm_smoke_detected
          - entity: binary_sensor.rookmelder_zolder_smoke_alarm_smoke_alarm_test
          - entity: sensor.rookmelder_zolder_battery_level
        show_header_toggle: false
        title: Rookmelder Zolder
        type: entities
      - entities:
          - entity: binary_sensor.rookmelder_woonkamer_smoke_alarm_smoke_detected
          - entity: binary_sensor.rookmelder_woonkamer_smoke_alarm_smoke_alarm_test
          - entity: sensor.rookmelder_woonkamer_battery_level
        show_header_toggle: false
        title: Rookmelder Woonkamer
        type: entities
      - entities:
          - entity: binary_sensor.koolmonoxidemelder_co_alarm_carbon_monoxide_detected
          - entity: binary_sensor.koolmonoxidemelder_co_alarm_carbon_monoxide_test
          - entity: sensor.koolmonoxidemelder_carbon_monoxide_co_level
          - entity: sensor.koolmonoxidemelder_battery_level
        show_header_toggle: false
        title: CO Melder
        type: entities
    icon: "mdi:shield-check"
    title: Veiligheid
  - badges: []
    cards:
      - entities:
          - entity: weather.home
        show_header_toggle: false
        type: entities
      - entities:
          - entity: sensor.garage_temperatuur
            name: Temperatuur
          - entity: sensor.garage_luchtvochtigheid
            name: Luchtvochtigheid
          - entity: sensor.buiten_temperatuur
            name: Buitentemperatuur
        show_header_toggle: false
        title: Garage
        type: entities
      - entities:
          - entity: sensor.slaapkamer_temperatuur
            name: Temperatuur
          - entity: sensor.slaapkamer_luchtvochtigheid
            name: Luchtvochtigheid
          - entity: sensor.slaapkamer_luchtdruk
            name: Luchtdruk
        show_header_toggle: false
        title: Slaapkamer
        type: entities
      - entities:
          - entity: sensor.woonkamer_temperatuur
            name: Temperatuur
          - entity: sensor.woonkamer_luchtvochtigheid
            name: Luchtvochtigheid
          - entity: sensor.woonkamer_luchtdruk
            name: Luchtdruk
        show_header_toggle: false
        title: Woonkamer
        type: entities
      - entities:
          - entity: sensor.rookmelder_zolder_air_temperature
            name: Zolder
          - entity: sensor.rookmelder_overloop_air_temperature
            name: Overloop
          - entity: sensor.rookmelder_hal_air_temperature
            name: Hal
          - entity: sensor.rookmelder_woonkamer_air_temperature
            name: Woonkamer
          - entity: sensor.koolmonoxidemelder_air_temperature
            name: Washok
        show_header_toggle: false
        title: Temperaturen Rookmelders
        type: entities
      - entities:
          - entity: sensor.temperatuurverschil_buiten_binnen
        show_header_toggle: false
        title: Temperatuurmonitoring
        type: entities
    icon: "mdi:thermometer-lines"
    title: Klimaat
  - badges:
      - entity: person.alex
      - entity: person.joyce
      - entity: sun.sun
    cards:
      - entities:
          - entity: sensor.smartmeter_power_consumption_2
            name: Power Consumption
          - entity: sensor.smartmeter_total_consumption_2
            name: Total
        show_header_toggle: false
        type: entities
      - entities:
          - entity: sensor.last_boot
          - entity: sensor.processor_use
          - entity: sensor.cpu_temperature
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.memory_use_percent
          - entity: sensor.swap_use_percent
          - entity: sensor.disk_use_percent
          - entity: sensor.disk_use_percent_boot
          - entity: sensor.disk_use_percent_srv_files_storage
          - entity: sensor.network_in_br0
          - entity: sensor.network_out_br0
        show_header_toggle: false
        title: PiCore1
        type: entities
    icon: "mdi:speedometer"
    title: Monitoring
