name: Thuis
views:
  - name: Woonkamer
    id: woonkamer
    icon: mdi:home-assistant
    cards:
      - id: 57340b89331f4028b47e15dae86fe065  # Automatically created id
        type: entities
        title: Scene Selectie
        entities:
          - input_select.media_scene
          - input_select.light_scene

      - id: 8dba8a82ddc24a9591ff1889a73f2d24  # Automatically created id
        type: glance
        title: Lampen Woonkamer
        show_state: false
        entities:
          - entity: light.spruitje
            tap_action: toggle
          - entity: light.linksvoor
            tap_action: toggle
          - entity: light.raam
            tap_action: toggle
          - entity: light.linksachter
            tap_action: toggle
          - entity: light.schilderij
            tap_action: toggle
          - entity: light.eettafel
            tap_action: toggle
          - entity: script.all_off
            tap_action: toggle

  - name: Slaapkamer
    id: slaapkamer
    icon: mdi:sleep
    cards:
      - id: 548530d3190c40fba07fa35c005abe09  # Automatically created id
        type: entities
        title: Bediening Slaapkamer
        show_header_toggle: false
        entities:
          - entity: light.achterwand_slaapkamer
          - entity: switch.tv_slaapkamer
          - entity: light.nachtlampje_alex
          - entity: light.nachtlampje_joyce
          - entity: script.timer_tv_slaapkamer

  - name: Apparaten
    id: apparaten
    icon: mdi:desktop-classic
    cards:
      - id: dd2d5528e4f242ae92d59c702abbd8bf  # Automatically created id
        type: glance
        title: Overige Lampen
        show_state: false
        entities:
          - entity: switch.hal_lamp
            name: Hal
            tap_action: toggle
          - entity: switch.hal_buitenlamp_voor
            name: Buiten
            tap_action: toggle
          - entity: switch.overloop_lamp
            name: Overloop
            tap_action: toggle

      - id: 072c460587b443a8818db9c13b9d1fb9  # Automatically created id
        type: glance
        title: Computers
        show_state: false
        entities:
          - entity: switch.nuc
            tap_action: toggle
          - entity: switch.server
            tap_action: toggle

      - id: 083aba24d440472aa003a4ff992dcb1e  # Automatically created id
        type: entities
        title: Mechanische Ventilatie
        show_header_toggle: false
        entities:
          - entity: fan.mechanische_ventilatie
          - entity: sensor.mv_vermogen
          - entity: sensor.mv_spanning
          - entity: sensor.mv_stroom
          - entity: sensor.mv_actief_vermogen
          - entity: sensor.mv_reactief_vermogen
          - entity: sensor.mv_power_factor

      - id: 19d55dca69594ed68b56db8bed456b67  # Automatically created id
        type: glance
        title: Mediaspelers
        show_state: false
        entities:
          - entity: media_player.receiver
            tap_action: toggle
          - entity: media_player.woonkamer
            tap_action: toggle

  - name: Veiligheid
    id: veiligheid
    icon: mdi:verified
    cards:
      - id: fba92bcbce3049c5b82d7e4704f20236  # Automatically created id
        type: entities
        title: Rookmelder Hal
        entities:
          - binary_sensor.rook_hal
          - binary_sensor.test_rookmelder_hal
          - sensor.rookmelder_hal_battery_level

      - id: e0dc7d99ff384fa682c92a239e85c425  # Automatically created id
        type: entities
        title: Rookmelder Overloop
        entities:
          - binary_sensor.rook_overloop
          - binary_sensor.test_rookmelder_overloop
          - sensor.rookmelder_overloop_battery_level

      - id: eef388ba8cbc4bf5a9605898ef5c14dc  # Automatically created id
        type: entities
        title: Rookmelder Zolder
        entities:
          - binary_sensor.rook_zolder
          - binary_sensor.test_rookmelder_zolder
          - sensor.rookmelder_zolder_battery_level

  - name: Klimaat
    id: klimaat
    icon: mdi:thermometer-lines
    cards:
      - id: eaefa499511d4b3aab2e115425a9fb93  # Automatically created id
        type: entities
        title: Binnenklimaat
        entities:
          - sensor.luchtvochtigheid_meterkast
          - sensor.temperatuur_meterkast
          - entity: sensor.rookmelder_hal_temperature
            name: Temperatuur Hal
          - entity: sensor.rookmelder_overloop_temperature
            name: Temperatuur Overloop
          - entity: sensor.rookmelder_zolder_temperature
            name: Temperatuur Zolder

  - name: Monitoring
    id: monitoring
    icon: mdi:speedometer
    cards:
      - id: 4ec122099a1945e3b024ffe9d38e1d86  # Automatically created id
        type: entities
        title: Smart Meter
        entities:
          - entity: sensor.smart_meter_power_consumption
            name: Power Consumption
          - entity: sensor.smart_meter_uptime
            name: Uptime
          - entity: sensor.smart_meter_wifi_signal
            name: WiFi Signaal

      - id: ad51348c087e43acbd5f4e678f9b01bb  # Automatically created id
        type: entities
        title: Up Squared
        entities:
          - sensor.since_last_boot
          - sensor.processor_use
          - sensor.cpu_temperature
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.memory_use_percent
          - sensor.swap_use_percent
          - sensor.disk_use_percent_
          - sensor.disk_use_percent_boot
          - sensor.disk_use_percent_mntstorage
          - sensor.disk_use_percent_mntcache
          - sensor.network_in_enp2s0
          - sensor.network_out_enp2s0
          - sensor.network_in_enp3s0
          - sensor.network_out_enp3s0
          - sensor.network_in_enp0s21f0u2u4
          - sensor.network_out_enp0s21f0u2u4

      - id: c65670a39fe14c5db3ec9fff8d57062a  # Automatically created id
        type: glance
        title: Aanwezigen
        show_state: false
        entities:
          - entity: device_tracker.alex
          - entity: device_tracker.joyce
          - entity: sun.sun

  - name: Settings
    id: settings
    icon: mdi:settings
    cards:
      - id: 21f5d51000384735ae6200580bc95282  # Automatically created id
        type: entities
        title: Toggles
        show_header_toggle: false
        entities:
          - input_boolean.admin_notifications

      - id: d795d2c473f047568c79a301319c8b01  # Automatically created id
        type: entities
        title: Logger Levels
        show_header_toggle: false
        entities:
          - input_select.logger_level_homeassistant
          - input_select.logger_level_zwave
          - input_select.logger_level_tradfri

  - name: Sonoff
    id: sonoff
    icon: mdi:switch
    cards:
      - id: c592682baad048f09dd78c5c0eea4742  # Automatically created id
        type: entities
        title: POW
        show_header_toggle: false
        entities:
          - binary_sensor.sonoff_pow_status
          - sensor.sonoff_pow_version
          - sensor.sonoff_pow_uptime
          - sensor.sonoff_pow_freeheap
          - sensor.sonoff_pow_rssi

      - id: 0ef9b5d4bfdb49588b1c0e0cbd031fb1  # Automatically created id
        type: entities
        title: 4CH
        show_header_toggle: false
        entities:
          - binary_sensor.sonoff_4ch_status
          - sensor.sonoff_4ch_version
          - sensor.sonoff_4ch_uptime
          - sensor.sonoff_4ch_freeheap
          - sensor.sonoff_4ch_rssi

      - id: b30b33cf9d464f80ac3e13db2b106941  # Automatically created id
        type: entities
        title: 4CH Pro
        show_header_toggle: false
        entities:
          - binary_sensor.sonoff_4ch_pro_status
          - sensor.sonoff_4ch_pro_version
          - sensor.sonoff_4ch_pro_uptime
          - sensor.sonoff_4ch_pro_freeheap
          - sensor.sonoff_4ch_pro_rssi

      - id: af3fd76c077046d19e0c65442420b3ec  # Automatically created id
        type: entities
        title: S20
        show_header_toggle: false
        entities:
          - binary_sensor.sonoff_s20_status
          - sensor.sonoff_s20_version
          - sensor.sonoff_s20_uptime
          - sensor.sonoff_s20_freeheap
          - sensor.sonoff_s20_rssi

      - id: dfcdd6971e4746738ec6ee3db4f517d1  # Automatically created id
        type: entities
        title: RF Bridge
        show_header_toggle: false
        entities:
          - binary_sensor.sonoff_rf_bridge_status
          - sensor.sonoff_rf_bridge_version
          - sensor.sonoff_rf_bridge_uptime
          - sensor.sonoff_rf_bridge_freeheap
          - sensor.sonoff_rf_bridge_rssi
          - sensor.sonoff_rf_bridge_rfin

