- platform: template
  sensors:
    alex_home:
      friendly_name: "Alex is thuis"
      value_template: "{{ is_state('device_tracker.alex', 'home') }}"
    joyce_home:
      friendly_name: "Joyce is thuis"
      value_template: "{{ is_state('device_tracker.joyce', 'home') }}"
    rook_hal:
      friendly_name: "Rook in de Hal"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_hal_smoke', '2') }}"
    test_rookmelder_hal:
      friendly_name: "TEST Rookmelder Hal"
      value_template: "{{ is_state('sensor.rookmelder_hal_smoke', '3') }}"
    rook_overloop:
      friendly_name: "Rook op de Overloop"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_overloop_smoke', '2') }}"
    test_rookmelder_overloop:
      friendly_name: "TEST Rookmelder Overloop"
      value_template: "{{ is_state('sensor.rookmelder_overloop_smoke', '3') }}"
    rook_zolder:
      friendly_name: "Rook op Zolder"
      device_class: "smoke"
      value_template: "{{ is_state('sensor.rookmelder_zolder_smoke', '2') }}"
    test_rookmelder_zolder:
      friendly_name: "TEST Rookmelder Zolder"
      value_template: "{{ is_state('sensor.rookmelder_zolder_smoke', '3') }}"
